apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gra-httpproxy
  namespace: tanzu-system-monitoring
spec:
  virtualhost:
    fqdn: nirs-gra.cnd.lab
    #tls:
    #  secretName: cnd-tls/wild-tls
  routes:
  - services:
    - name: grafana
      port: 80
    conditions:
    - prefix: /
      #pathRewritePolicy:
      #replacePrefix:
      # - prefix: /
      #  replacement: 



